name: "Linter: shellcheck"
on:
  push:
    branches:
      - "**"
    paths:
      - "boards/**"
      - "scripts/**"
      # Add workflow itself for now
      - ".github/workflows/ShellCheck.yml"

  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - "**"
    paths:
      - "config/**"
      - "src/**"
      - "!src/version"

  workflow_dispatch:

jobs:
  lint_scripts:
    name: Shellcheck (scripts)
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Check all scripts are executable
        run: ./scripts/ensure-executable-scripts.sh

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -ax -s bash
        with:
          scandir: "./scripts"
          format: tty

      - name: Failure Summary
        if: failure()
        run: |
          echo "## Shellcheck failed! :no_entry:" >> $GITHUB_STEP_SUMMARY
          echo "_Please check Annotations for details ..._ :point_up:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "These Errors have to be corrected, before the changes can be accepted :exclamation:" >> $GITHUB_STEP_SUMMARY
      - name: Success Summary
        if: success()
        run: |
          echo "## Shellcheck succeeded :tada:" >> $GITHUB_STEP_SUMMARY
          echo "Well done .. :white_check_mark:" >> $GITHUB_STEP_SUMMARY
  lint_boards:
    name: Shellcheck (boards)
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Run ShellCheck
        id: boards
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -ax -s bash
        with:
          scandir: "./boards"
          format: tty

      - name: Failure Summary
        if: failure()
        run: |
          echo "## Shellcheck failed! :no_entry:" >> $GITHUB_STEP_SUMMARY
          echo "_Please check Annotations for details ..._ :point_up:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "These Errors have to be corrected, before the changes can be accepted :exclamation:" >> $GITHUB_STEP_SUMMARY
      - name: Success Summary
        if: success()
        run: |
          echo "## Shellcheck succeeded :tada:" >> $GITHUB_STEP_SUMMARY
          echo "Well done .. :white_check_mark:" >> $GITHUB_STEP_SUMMARY
